project:
  type: book

book:
  title: "A collection of tutorials and scripts"
  author: "Javier Carpinteyro Ponce"
  chapters:
    - index.qmd
    - part: "All about GitHub"
      chapters:
        - github/getstarted_localrepo.qmd
    - part: "All about micromamba"
      chapters:
        - micromamba/getstarted_HPC.qmd

format:
  html:
    number-sections: false